language: php
php:
  - '5.4'
  - '5.6'
  - '7.0'
  - hhvm # on Trusty only
  - nightly
env:
  - DB=mysql
  - DB=pgsql

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS bookstore;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database bookstore;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS bookstore;" -uroot; fi

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit --configuration phpunit_$DB.xml --coverage-text

# configure notifications (email, IRC, campfire etc)
notifications:
  irc: "irc.freenode.org#yourfavouriteroomfortravis"
