language: php
php:
  - '7.0'
  - '7.1'
services:
  - mysql


before_script:
  - cp .env.travis .env
  - sudo mysql -e 'create database bookstore;'
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate