language: php
php:
  - '7.0'
  - '7.1'
services:
  - mysql
before_script:
- mysql -e 'create database bookstore;'
- composer self-update
- php artisan key:generate
- php artisan migrate --seed

script:
    - API/php/db
