language: php
php:
  - '7.0'
  - nightly
env:
  - DB=mysql
services:
  - mysql  

# execute any number of scripts before the test run, custom env's are available as variables
before_install:
  - mysql -e "create database IF NOT EXISTS bookstore;"

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit --configuration db.php --coverage-text

# configure notifications (email, IRC, campfire etc)
notifications:
  irc: "irc.freenode.org#yourfavouriteroomfortravis"
